# Generated by Django 4.2.15 on 2024-09-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='final_price',
            field=models.IntegerField(default=0),
        ),
    ]
