# Generated by Django 4.2.15 on 2024-09-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_final_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Brand_name',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='final_price',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='model_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='price',
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
