# Generated by Django 4.2.15 on 2024-09-04 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0004_customer_product_ref'),
        ('product', '0002_remove_product_product_name_product_brand_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('gst', models.FloatField(default=0)),
                ('final_price', models.FloatField(default=0)),
                ('customer_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('product_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
    ]
